SELECT J.FLAVOR
FROM FIRST_HALF FH
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) TOTAL_ORDER
     FROM JULY
     GROUP BY FLAVOR) J
ON FH.FLAVOR = J.FLAVOR
ORDER BY (FH.TOTAL_ORDER + J.TOTAL_ORDER) DESC  -- 내림차순 
LIMIT 3;  -- 3개 조회